# Generated by Django 3.2.13 on 2022-05-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('supply', models.FloatField()),
                ('min_limit', models.FloatField()),
                ('max_limit', models.FloatField()),
                ('lot_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='sell', max_length=200)),
                ('currency', models.CharField(choices=[('eth', 'Eth'), ('kzt', 'Kzt')], default='kzt', max_length=200)),
            ],
        ),
    ]
