# Generated by Django 3.2.13 on 2022-05-22 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('requisite_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('supply', models.FloatField()),
                ('min_limit', models.FloatField()),
                ('max_limit', models.FloatField()),
                ('lot_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='sell', max_length=200)),
                ('currency', models.CharField(choices=[('eth', 'Eth'), ('kzt', 'Kzt')], default='kzt', max_length=200)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.payment')),
            ],
        ),
    ]
