# Generated by Django 3.2.13 on 2022-05-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('phone', 'Phone'), ('bank_number', 'Bank Num')], default='phone', max_length=200),
        ),
        migrations.RemoveField(
            model_name='lot',
            name='payment',
        ),
        migrations.AddField(
            model_name='lot',
            name='payment',
            field=models.ManyToManyField(to='app.Payment'),
        ),
    ]
