# Generated by Django 3.2.13 on 2022-06-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="is_active",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
