# Generated by Django 3.2.13 on 2022-05-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='buyer_id',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='seller_name',
        ),
        migrations.AddField(
            model_name='lot',
            name='currency',
            field=models.CharField(choices=[('eth', 'Eth'), ('kzt', 'Kzt')], default='kzt', max_length=200),
        ),
        migrations.AddField(
            model_name='lot',
            name='lot_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='sell', max_length=200),
        ),
        migrations.AddField(
            model_name='lot',
            name='max_limit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lot',
            name='min_limit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lot',
            name='supply',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
